services:
  # Backend Application (Laravel)
  tta-backend:
    build:
      context: .
      dockerfile: .docker/php/prod.Dockerfile
    image: tta-backend-image
    container_name: tta-backend
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - "8080:8080"
    volumes:
      - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - tta-network
    depends_on:
      - tta-db

  # Backend Nginx (serving Laravel)
  tta-nginx-backend:
    build:
      context: .
      dockerfile: .docker/nginx/dockerfile/prod.Dockerfile
    container_name: tta-nginx-backend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - tta-network
    depends_on:
      - tta-backend

  # Database
  tta-db:
    image: postgres:latest
    container_name: tta-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - tta-db-data:/var/lib/postgresql/data
    networks:
      - tta-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis
  tta-redis:
    image: redis:alpine
    container_name: tta-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - tta-redis-data:/data
    networks:
      - tta-network

networks:
  tta-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.31.0.0/24"
          gateway: 172.31.0.1

volumes:
  tta-db-data:
    driver: local
  tta-redis-data:
    driver: local
